apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-storage
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  bucket: kube-bucket
  endpoint: http://minio.storage.svc.cluster.local:9000
  region: us-east-1
reclaimPolicy: Delete
volumeBindingMode: Immediate